export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";


export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const REMOVE_POST_REQUEST = 'REMOVE_POST_REQUEST';
export const REMOVE_POST_ERROR = 'REMOVE_POST_ERROR';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR';

export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_REQUEST = 'REMOVE_COMMENT_REQUEST';
export const REMOVE_COMMENT_ERROR = 'REMOVE_COMMENT_ERROR';

export const FETCH_FORUM_HEADRS_REQUEST = 'FETCH_FORUM_HEADRS_REQUEST';
export const FETCH_FORUM_HEADRS_SUCCESS = 'FETCH_FORUM_HEADRS_SUCCESS';
export const FETCH_FORUM_HEADRS_ERROR = 'FETCH_FORUM_HEADRS_ERROR';

export const FETCH_POSTS_BY_TOPIC_REQUEST = 'FETCH_POSTS_BY_TOPIC_REQUEST'
export const FETCH_POSTS_BY_TOPIC_ERROR = 'FETCH_POSTS_BY_TOPIC_ERROR'
export const FETCH_POSTS_BY_TOPIC_SUCCESS = 'FETCH_POSTS_BY_TOPIC_SUCCESS'

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';1