export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const REMOVE_POST_REQUEST = 'REMOTE_POST_REQUEST';
export const REMOVE_POST_ERROR = 'REMOVE_POST_ERROR';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR';

export const REMOVE_COMMENET_SUCCESS = 'REMOVE_COMMENET_SUCCESS';
export const REMOVE_COIMMENT_REQUEST = 'REMOVE_COIMMENT_REQUEST';
export const REMOVE_COMMENT_ERROR = 'REMOVE_COMMENT_ERROR';