export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const REMOVE_POST_REQUEST = "REMOVE_POST_REQUEST";
export const REMOVE_POST_ERROR = "REMOVE_POST_ERROR";
export const REMOVE_POST_SUCCESS = "REMOVE_POST_SUCCESS";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR";

export const REMOVE_COMMENT_SUCCESS = "REMOVE_COMMENT_SUCCESS";
export const REMOVE_COMMENT_REQUEST = "REMOVE_COMMENT_REQUEST";
export const REMOVE_COMMENT_ERROR = "REMOVE_COMMENT_ERROR";

export const FETCH_FORUM_HEADRS_REQUEST = "FETCH_FORUM_HEADRS_REQUEST";
export const FETCH_FORUM_HEADRS_SUCCESS = "FETCH_FORUM_HEADRS_SUCCESS";
export const FETCH_FORUM_HEADRS_ERROR = "FETCH_FORUM_HEADRS_ERROR";

export const FETCH_POSTS_BY_TOPIC_REQUEST = "FETCH_POSTS_BY_TOPIC_REQUEST";
export const FETCH_POSTS_BY_TOPIC_ERROR = "FETCH_POSTS_BY_TOPIC_ERROR";
export const FETCH_POSTS_BY_TOPIC_SUCCESS = "FETCH_POSTS_BY_TOPIC_SUCCESS";

export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_ERROR = "FETCH_POST_ERROR";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
1;

export const VOTE_POST_REQUEST = "VOTE_POST_REQUEST";
export const VOTE_POST_ERROR = "VOTE_POST_ERROR";
export const VOTE_POST_SUCCESS = "VOTE_POST_SUCCESS";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

export const UPLOAD_USER_IMAGE = "UPLOAD_USER_IMAGE";
export const DISCARD_USER_IMAGE = "DISCARD_USER_IMAGE";
export const DISCARD_USER_IMAGE_SUCCESS = "DISCARD_USER_IMAGE_SUCCESS";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";

export const EDIT_COMMENT_REQUEST = "EDIT_COMMENT_REQUEST";
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";

export const VOTE_COMMENT_REQUEST = "VOTE_COMMENT_REQUEST";
export const VOTE_COMMENT_ERROR = "VOTE_COMMENT_ERROR";
export const VOTE_COMMENT_SUCCESS = "VOTE_COMMENT_SUCCESS";

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_ERROR = "FETCH_COMMENTS_ERROR";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";

export const RESET_POST_DATA = "RESET_POST_DATA";

export const TOGGLE_SAVE_POST_REQUEST = "TOGGLE_SAVE_POST_REQUEST";
export const TOGGLE_SAVE_POST_ERROR = "TOGGLE_SAVE_POST_ERROR";
export const TOGGLE_SAVE_POST_SUCCESS = "TOGGLE_SAVE_POST_SUCCESS";

export const FETCH_SAVED_POSTS_REQUEST = 'FETCH_SAVED_POSTS_REQUEST';
export const FETCH_SAVED_POSTS_ERROR = 'FETCH_SAVED_POSTS_ERROR';
export const FETCH_SAVED_POSTS_SUCCESS = 'FETCH_SAVED_POSTS_SUCCESS';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'